### Site Settings ###
title               : Hi.
description         : >-
                      Hi. I make stuff.
                      Sometimes.
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : erytau/erytau.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : LeNPaul/portfolio-jekyll-theme


### Plugins ###
plugins:
  - jekyll-remote-theme
